### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ryenasti** [NixSey/STGGO#1]
![image](https://user-images.githubusercontent.com/107561821/174975592-fb38a1b0-ba99-46a1-99d5-bd7fe8801668.png)
nge stuck gini mulu

**Comment by Mr-Silenz** [comment]
Me too

**Comment by NixSey** [comment]
iyh emg gitu, kalo mau liat live traffic nya print response nya aja.

**Comment by ryenasti** [comment]
> 

gmn tuh caranya bg?, ga ngerti code soalnya 😅

**Comment by NixSey** [comment]
kasih `fmt.Printf("##### %d #####\n", res.StatusCode)` diatas `defer res.Body.Close()`

lalu kasih `fmt.Printf("%s\n", text)` dibawah `func pr(text string)`

**Comment by NixSey** [comment]
Use Latest Update to avoid Bugs, Errors & Crash. Thank you!
